#!/bin/bash

set -euo pipefail

IMAGE_NAME="${IMAGE_NAME:-brimstone/blinktd:latest}"

# stolen from https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
for GOARCH in amd64 arm; do
  docker build \
	           --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
               --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
               --build-arg GOARCH="${GOARCH}" \
               -t "$IMAGE_NAME"-"${GOARCH}" .
done
